package com.sinohealth.dscp.mapper;

import com.sinohealth.dscp.model.Drug;
import org.apache.ibatis.annotations.*;

import java.util.Date;
import java.util.List;

@Mapper
public interface DrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    int insert(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    int insertSelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    Drug selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Drug record);

    int insertDrugList(List<Drug> drugs);

    //注解方式一定要为每个字段添加别名
    @Select("select id,create_time createTime,create_user createUser,role_status roleStatus,role_name roleName,update_time updateTime,update_user updateUser from t_drug where id=#{id}")
    Drug selectDrugById(@Param("id") int id);

    @Select("select id,create_time createTime,create_user createUser,role_status roleStatus,role_name roleName,update_time updateTime,update_user updateUser from t_drug")
    List<Drug> selectDrugs();

    @Insert("insert into t_drug(create_time,create_user,role_name,role_status,update_time,update_user) values(#{create_time},#{create_user},#{role_name},#{role_status},#{update_time},#{update_user})")
    int insertDrug(@Param("create_time") Date create_time,@Param("create_user") String create_user,@Param("role_name") String role_name,@Param("role_status") int role_status,@Param("update_time") Date update_time,@Param("update_user") String update_user);

    @Delete("delete from t_drug where id=#{id}")
    int deleteDrugById(@Param("id") int id);

    @Update("update t_drug set create_time=#{create_time},update_time=#{update_time} where id=#{id}")
    int updateDrug(@Param("create_time")Date create_time,@Param("update_time")Date update_time,@Param("id")int id);

    @Delete("truncate table t_drug")
    int truncateTable();

    @Select("select count(1) from t_drug")
    int getCountForDrug();
}