server:
  port: 8086

spring:
  profiles:
    active: test
  application:
    name: userService

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dscp_user?characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show_sql: true
    format_sql: true
    database: MYSQL
    generate-ddl: true
    open-in-view: true
    hibernate:
      hbm2ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  zipkin:
    base-url: http://localhost:8087

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  session:
    timeout: 1200000

logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.mongcent.tnaot: debug
    org.springfromework: info
    org.hibernate: error
  file: log/user-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/